// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wa.infrastructure.Persistence;

#nullable disable

namespace wa.infrastructure.Migrations
{
    [DbContext(typeof(WaDbContext))]
    [Migration("20260901010036_SeedPlansAndFeatureFlags")]
    partial class SeedPlansAndFeatureFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wa.domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("EmailConfirmed");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlanId");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("system")
                        .HasColumnName("Theme");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppUser_Email");

                    b.HasIndex("PlanId");

                    b.ToTable("AppUser", "dbo");
                });

            modelBuilder.Entity("wa.domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Action");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("ActorEmail");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DetailsJson");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("EntityType");

                    b.HasKey("Id")
                        .HasName("PK_Audit");

                    b.ToTable("AuditLog", "dbo");
                });

            modelBuilder.Entity("wa.domain.AuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresAtUtc");

                    b.Property<byte>("Purpose")
                        .HasColumnType("tinyint")
                        .HasColumnName("Purpose");

                    b.Property<DateTime?>("RedeemedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RedeemedAtUtc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("TokenHash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_AuthToken_Hash");

                    b.ToTable("AuthToken", "dbo");
                });

            modelBuilder.Entity("wa.domain.BlobRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("BlobPath");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("PhysicallyDeletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("PhysicallyDeletedAtUtc");

                    b.Property<int>("RefCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("RefCount");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("SizeBytes");

                    b.HasKey("Id");

                    b.HasIndex("BlobPath")
                        .IsUnique()
                        .HasDatabaseName("UQ_BlobRef_Path");

                    b.HasIndex("PhysicallyDeletedAtUtc")
                        .HasDatabaseName("IX_BlobRef_Cleanup")
                        .HasFilter("RefCount = 0 AND PhysicallyDeletedAtUtc IS NOT NULL");

                    b.ToTable("BlobRef", "dbo");
                });

            modelBuilder.Entity("wa.domain.DownloadEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FileId");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("IpHash");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransferId");

                    b.Property<string>("UaHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("UaHash");

                    b.HasKey("Id")
                        .HasName("PK_DownEvent");

                    b.HasIndex("TransferId", "CreatedAtUtc")
                        .HasDatabaseName("IX_DownEvent_T");

                    b.ToTable("DownloadEvent", "dbo");
                });

            modelBuilder.Entity("wa.domain.EmailRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("Address");

                    b.Property<DateTime?>("NotifiedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("NotifiedAtUtc");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransferId");

                    b.HasKey("Id")
                        .HasName("PK_ER");

                    b.HasIndex("TransferId", "Address")
                        .IsUnique()
                        .HasDatabaseName("UQ_ER");

                    b.ToTable("EmailRecipient", "dbo");
                });

            modelBuilder.Entity("wa.domain.EmailSuppression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("Address");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("SenderEmail");

                    b.HasKey("Id")
                        .HasName("PK_ES");

                    b.HasIndex("Address", "SenderEmail")
                        .IsUnique()
                        .HasDatabaseName("UQ_ES")
                        .HasFilter("[SenderEmail] IS NOT NULL");

                    b.ToTable("EmailSuppression", "dbo");
                });

            modelBuilder.Entity("wa.domain.FeatureFlag", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Key");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.HasKey("Key")
                        .HasName("PK_Flag");

                    b.ToTable("FeatureFlag", "dbo");

                    b.HasData(
                        new
                        {
                            Key = "feature.ads",
                            Description = "Free-tier ads on/off (D-14: off at MVP launch)",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.scheduling",
                            Description = "Scheduled send global gate",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.analytics",
                            Description = "Download analytics global gate",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.resend",
                            Description = "Re-send global gate",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.collect",
                            Description = "Collect global gate (Phase 2a)",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.sign",
                            Description = "Sign global gate (Phase 2b)",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.albums",
                            Description = "Albums global gate (Phase 2c)",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.search",
                            Description = "Search global gate (F-XCT-002)",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.dataExport",
                            Description = "GDPR data export gate (F-XCT-004)",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.emailSettings",
                            Description = "Email settings global gate (F-XCT-001)",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.branding",
                            Description = "Branding global gate",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "feature.ssoScim",
                            Description = "SSO/SCIM global gate (F-ENT-001, per Part-2 SSO_SCIM)",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "limits.free.maxTransferSize",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5368709120"
                        },
                        new
                        {
                            Key = "limits.free.maxSingleFile",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5368709120"
                        },
                        new
                        {
                            Key = "limits.free.maxZipSize",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "4294967296"
                        },
                        new
                        {
                            Key = "limits.free.retentionDays",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "7"
                        },
                        new
                        {
                            Key = "limits.free.graceDays",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3"
                        },
                        new
                        {
                            Key = "limits.free.maxDownloads",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "100"
                        },
                        new
                        {
                            Key = "limits.free.maxEmails",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "20"
                        },
                        new
                        {
                            Key = "limits.free.storageQuota",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5368709120"
                        },
                        new
                        {
                            Key = "limits.free.activeTransfersMax",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "20"
                        },
                        new
                        {
                            Key = "limits.free.scheduling",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "limits.free.branding",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "limits.free.analytics",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "limits.free.ads",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "limits.free.ssoScim",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "limits.pro.maxTransferSize",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10737418240"
                        },
                        new
                        {
                            Key = "limits.pro.maxSingleFile",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10737418240"
                        },
                        new
                        {
                            Key = "limits.pro.maxZipSize",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "9223372036854775807"
                        },
                        new
                        {
                            Key = "limits.pro.retentionDays",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "30"
                        },
                        new
                        {
                            Key = "limits.pro.graceDays",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3"
                        },
                        new
                        {
                            Key = "limits.pro.maxDownloads",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1000"
                        },
                        new
                        {
                            Key = "limits.pro.maxEmails",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "100"
                        },
                        new
                        {
                            Key = "limits.pro.storageQuota",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "107374182400"
                        },
                        new
                        {
                            Key = "limits.pro.activeTransfersMax",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "200"
                        },
                        new
                        {
                            Key = "limits.pro.scheduling",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            Key = "limits.pro.branding",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            Key = "limits.pro.analytics",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            Key = "limits.pro.ads",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "limits.pro.ssoScim",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "limits.business.maxTransferSize",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "107374182400"
                        },
                        new
                        {
                            Key = "limits.business.maxSingleFile",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "107374182400"
                        },
                        new
                        {
                            Key = "limits.business.maxZipSize",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "9223372036854775807"
                        },
                        new
                        {
                            Key = "limits.business.retentionDays",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "90"
                        },
                        new
                        {
                            Key = "limits.business.graceDays",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3"
                        },
                        new
                        {
                            Key = "limits.business.maxDownloads",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "-1"
                        },
                        new
                        {
                            Key = "limits.business.maxEmails",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "500"
                        },
                        new
                        {
                            Key = "limits.business.storageQuota",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1099511627776"
                        },
                        new
                        {
                            Key = "limits.business.activeTransfersMax",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "-1"
                        },
                        new
                        {
                            Key = "limits.business.scheduling",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            Key = "limits.business.branding",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            Key = "limits.business.analytics",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            Key = "limits.business.ads",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "limits.business.ssoScim",
                            Description = "Plan limits override (TA-3.4); values per Open-Decisions Part 2",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        });
                });

            modelBuilder.Entity("wa.domain.FileItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("BlobRefId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlobRefId");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ContentType");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("OriginalName");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("SizeBytes");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransferId");

                    b.HasKey("Id");

                    b.HasIndex("BlobRefId");

                    b.HasIndex("TransferId", "BlobRefId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FileItem_T_B");

                    b.HasIndex("TransferId", "SortOrder")
                        .HasDatabaseName("IX_FileItem_T");

                    b.ToTable("FileItem", "dbo");
                });

            modelBuilder.Entity("wa.domain.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresAtUtc");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResultJson");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransferId");

                    b.HasKey("Key")
                        .HasName("PK_Idem");

                    b.ToTable("IdempotencyKey", "dbo");
                });

            modelBuilder.Entity("wa.domain.JobRun", b =>
                {
                    b.Property<string>("JobKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("JobKey");

                    b.Property<DateTime>("RunAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RunAtUtc");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FinishedAtUtc");

                    b.Property<DateTime>("LockUntilUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("LockUntilUtc");

                    b.HasKey("JobKey", "RunAtUtc");

                    b.ToTable("JobRun", "dbo");
                });

            modelBuilder.Entity("wa.domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Code");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FeaturesJson");

                    b.Property<string>("LimitsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LimitsJson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("Name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SortOrder");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Plan_Code");

                    b.ToTable("Plan", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-4000-8000-000000000001"),
                            Code = "free",
                            FeaturesJson = "{\"ads\":false,\"scheduling\":false,\"analytics\":false,\"branding\":false,\"sso_scim\":false}",
                            LimitsJson = "{\"maxTransferSize\":5368709120,\"maxSingleFile\":5368709120,\"maxZipSize\":4294967296,\"retentionDays\":7,\"graceDays\":3,\"maxDownloads\":100,\"maxEmails\":20,\"storageQuota\":5368709120,\"activeTransfersMax\":20}",
                            Name = "Free",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-4000-8000-000000000002"),
                            Code = "pro",
                            FeaturesJson = "{\"ads\":false,\"scheduling\":true,\"analytics\":true,\"branding\":true,\"sso_scim\":false}",
                            LimitsJson = "{\"maxTransferSize\":10737418240,\"maxSingleFile\":10737418240,\"maxZipSize\":9223372036854775807,\"retentionDays\":30,\"graceDays\":3,\"maxDownloads\":1000,\"maxEmails\":100,\"storageQuota\":107374182400,\"activeTransfersMax\":200}",
                            Name = "Pro",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-4000-8000-000000000003"),
                            Code = "business",
                            FeaturesJson = "{\"ads\":false,\"scheduling\":true,\"analytics\":true,\"branding\":true,\"sso_scim\":true}",
                            LimitsJson = "{\"maxTransferSize\":107374182400,\"maxSingleFile\":107374182400,\"maxZipSize\":9223372036854775807,\"retentionDays\":90,\"graceDays\":3,\"maxDownloads\":-1,\"maxEmails\":500,\"storageQuota\":1099511627776,\"activeTransfersMax\":-1}",
                            Name = "Business",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("wa.domain.StripeEvent", b =>
                {
                    b.Property<string>("StripeEventId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StripeEventId");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ProcessedAtUtc");

                    b.HasKey("StripeEventId");

                    b.ToTable("StripeEvent", "dbo");
                });

            modelBuilder.Entity("wa.domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("CurrentPeriodEndUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CurrentPeriodEndUtc");

                    b.Property<DateTime?>("GraceEndsAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("GraceEndsAtUtc");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("PlanCode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StripeCustomerId");

                    b.Property<string>("StripeSubId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StripeSubId");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.HasKey("Id")
                        .HasName("PK_Sub");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StripeSubId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Sub_Stripe");

                    b.ToTable("Subscription", "dbo");
                });

            modelBuilder.Entity("wa.domain.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<int>("DownloadsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("DownloadsCount");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiredAtUtc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresAtUtc");

                    b.Property<int>("FileCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("FileCount");

                    b.Property<string>("LinkId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("LinkId");

                    b.Property<int>("MaxDownloads")
                        .HasColumnType("int")
                        .HasColumnName("MaxDownloads");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Note");

                    b.Property<Guid?>("OwnerAppUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnerAppUserId");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<DateTime?>("ScheduledSendAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ScheduledSendAtUtc");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("SenderEmail");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SenderName");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("Status");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SupersededBy");

                    b.Property<long>("TotalBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("TotalBytes");

                    b.HasKey("Id");

                    b.HasIndex("LinkId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Transfer_LinkId");

                    b.HasIndex("SupersededBy");

                    b.HasIndex("OwnerAppUserId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Transfer_Owner");

                    b.HasIndex("Status", "ExpiresAtUtc")
                        .HasDatabaseName("IX_Transfer_Expiry");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "ExpiresAtUtc"), new[] { "Id" });

                    b.HasIndex("Status", "ScheduledSendAtUtc")
                        .HasDatabaseName("IX_Transfer_Sched");

                    b.ToTable("Transfer", "dbo");
                });

            modelBuilder.Entity("wa.domain.AppUser", b =>
                {
                    b.HasOne("wa.domain.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AppUser_Plan");
                });

            modelBuilder.Entity("wa.domain.EmailRecipient", b =>
                {
                    b.HasOne("wa.domain.Transfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ER_T");
                });

            modelBuilder.Entity("wa.domain.FileItem", b =>
                {
                    b.HasOne("wa.domain.BlobRef", null)
                        .WithMany()
                        .HasForeignKey("BlobRefId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_FileItem_B");

                    b.HasOne("wa.domain.Transfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_FileItem_T");
                });

            modelBuilder.Entity("wa.domain.Subscription", b =>
                {
                    b.HasOne("wa.domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Sub_U");
                });

            modelBuilder.Entity("wa.domain.Transfer", b =>
                {
                    b.HasOne("wa.domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Transfer_Owner");

                    b.HasOne("wa.domain.Transfer", null)
                        .WithMany()
                        .HasForeignKey("SupersededBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_T_Super");
                });
#pragma warning restore 612, 618
        }
    }
}
