// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wa.infrastructure.Persistence;

#nullable disable

namespace wa.infrastructure.Migrations
{
    [DbContext(typeof(WaDbContext))]
    partial class WaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wa.domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("EmailConfirmed");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlanId");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("system")
                        .HasColumnName("Theme");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppUser_Email");

                    b.HasIndex("PlanId");

                    b.ToTable("AppUser", "dbo");
                });

            modelBuilder.Entity("wa.domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Action");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("ActorEmail");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DetailsJson");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("EntityType");

                    b.HasKey("Id")
                        .HasName("PK_Audit");

                    b.ToTable("AuditLog", "dbo");
                });

            modelBuilder.Entity("wa.domain.AuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresAtUtc");

                    b.Property<byte>("Purpose")
                        .HasColumnType("tinyint")
                        .HasColumnName("Purpose");

                    b.Property<DateTime?>("RedeemedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RedeemedAtUtc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("TokenHash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_AuthToken_Hash");

                    b.ToTable("AuthToken", "dbo");
                });

            modelBuilder.Entity("wa.domain.BlobRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("BlobPath");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("PhysicallyDeletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("PhysicallyDeletedAtUtc");

                    b.Property<int>("RefCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("RefCount");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("SizeBytes");

                    b.HasKey("Id");

                    b.HasIndex("BlobPath")
                        .IsUnique()
                        .HasDatabaseName("UQ_BlobRef_Path");

                    b.HasIndex("PhysicallyDeletedAtUtc")
                        .HasDatabaseName("IX_BlobRef_Cleanup")
                        .HasFilter("RefCount = 0 AND PhysicallyDeletedAtUtc IS NOT NULL");

                    b.ToTable("BlobRef", "dbo");
                });

            modelBuilder.Entity("wa.domain.DownloadEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FileId");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("IpHash");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransferId");

                    b.Property<string>("UaHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("UaHash");

                    b.HasKey("Id")
                        .HasName("PK_DownEvent");

                    b.HasIndex("TransferId", "CreatedAtUtc")
                        .HasDatabaseName("IX_DownEvent_T");

                    b.ToTable("DownloadEvent", "dbo");
                });

            modelBuilder.Entity("wa.domain.EmailRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("Address");

                    b.Property<DateTime?>("NotifiedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("NotifiedAtUtc");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransferId");

                    b.HasKey("Id")
                        .HasName("PK_ER");

                    b.HasIndex("TransferId", "Address")
                        .IsUnique()
                        .HasDatabaseName("UQ_ER");

                    b.ToTable("EmailRecipient", "dbo");
                });

            modelBuilder.Entity("wa.domain.EmailSuppression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("Address");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("SenderEmail");

                    b.HasKey("Id")
                        .HasName("PK_ES");

                    b.HasIndex("Address", "SenderEmail")
                        .IsUnique()
                        .HasDatabaseName("UQ_ES")
                        .HasFilter("[SenderEmail] IS NOT NULL");

                    b.ToTable("EmailSuppression", "dbo");
                });

            modelBuilder.Entity("wa.domain.FeatureFlag", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Key");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.HasKey("Key")
                        .HasName("PK_Flag");

                    b.ToTable("FeatureFlag", "dbo");
                });

            modelBuilder.Entity("wa.domain.FileItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("BlobRefId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlobRefId");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ContentType");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("OriginalName");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("SizeBytes");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransferId");

                    b.HasKey("Id");

                    b.HasIndex("BlobRefId");

                    b.HasIndex("TransferId", "BlobRefId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FileItem_T_B");

                    b.HasIndex("TransferId", "SortOrder")
                        .HasDatabaseName("IX_FileItem_T");

                    b.ToTable("FileItem", "dbo");
                });

            modelBuilder.Entity("wa.domain.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresAtUtc");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResultJson");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransferId");

                    b.HasKey("Key")
                        .HasName("PK_Idem");

                    b.ToTable("IdempotencyKey", "dbo");
                });

            modelBuilder.Entity("wa.domain.JobRun", b =>
                {
                    b.Property<string>("JobKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("JobKey");

                    b.Property<DateTime>("RunAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RunAtUtc");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FinishedAtUtc");

                    b.Property<DateTime>("LockUntilUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("LockUntilUtc");

                    b.HasKey("JobKey", "RunAtUtc");

                    b.ToTable("JobRun", "dbo");
                });

            modelBuilder.Entity("wa.domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Code");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FeaturesJson");

                    b.Property<string>("LimitsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LimitsJson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("Name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SortOrder");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Plan_Code");

                    b.ToTable("Plan", "dbo");
                });

            modelBuilder.Entity("wa.domain.StripeEvent", b =>
                {
                    b.Property<string>("StripeEventId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StripeEventId");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ProcessedAtUtc");

                    b.HasKey("StripeEventId");

                    b.ToTable("StripeEvent", "dbo");
                });

            modelBuilder.Entity("wa.domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("CurrentPeriodEndUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CurrentPeriodEndUtc");

                    b.Property<DateTime?>("GraceEndsAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("GraceEndsAtUtc");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("PlanCode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StripeCustomerId");

                    b.Property<string>("StripeSubId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StripeSubId");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.HasKey("Id")
                        .HasName("PK_Sub");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StripeSubId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Sub_Stripe");

                    b.ToTable("Subscription", "dbo");
                });

            modelBuilder.Entity("wa.domain.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAtUtc");

                    b.Property<int>("DownloadsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("DownloadsCount");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiredAtUtc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresAtUtc");

                    b.Property<int>("FileCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("FileCount");

                    b.Property<string>("LinkId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("LinkId");

                    b.Property<int>("MaxDownloads")
                        .HasColumnType("int")
                        .HasColumnName("MaxDownloads");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Note");

                    b.Property<Guid?>("OwnerAppUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnerAppUserId");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<DateTime?>("ScheduledSendAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ScheduledSendAtUtc");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("SenderEmail");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SenderName");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("Status");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SupersededBy");

                    b.Property<long>("TotalBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("TotalBytes");

                    b.HasKey("Id");

                    b.HasIndex("LinkId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Transfer_LinkId");

                    b.HasIndex("SupersededBy");

                    b.HasIndex("OwnerAppUserId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Transfer_Owner");

                    b.HasIndex("Status", "ExpiresAtUtc")
                        .HasDatabaseName("IX_Transfer_Expiry");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "ExpiresAtUtc"), new[] { "Id" });

                    b.HasIndex("Status", "ScheduledSendAtUtc")
                        .HasDatabaseName("IX_Transfer_Sched");

                    b.ToTable("Transfer", "dbo");
                });

            modelBuilder.Entity("wa.domain.AppUser", b =>
                {
                    b.HasOne("wa.domain.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AppUser_Plan");
                });

            modelBuilder.Entity("wa.domain.EmailRecipient", b =>
                {
                    b.HasOne("wa.domain.Transfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ER_T");
                });

            modelBuilder.Entity("wa.domain.FileItem", b =>
                {
                    b.HasOne("wa.domain.BlobRef", null)
                        .WithMany()
                        .HasForeignKey("BlobRefId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_FileItem_B");

                    b.HasOne("wa.domain.Transfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_FileItem_T");
                });

            modelBuilder.Entity("wa.domain.Subscription", b =>
                {
                    b.HasOne("wa.domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Sub_U");
                });

            modelBuilder.Entity("wa.domain.Transfer", b =>
                {
                    b.HasOne("wa.domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Transfer_Owner");

                    b.HasOne("wa.domain.Transfer", null)
                        .WithMany()
                        .HasForeignKey("SupersededBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_T_Super");
                });
#pragma warning restore 612, 618
        }
    }
}
