<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\wa.infrastructure\wa.infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreRateLimit" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.ApplicationInsights" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
